spring.application.name=subdel

spring.main.allow-bean-definition-overriding=true
dgs.graphql.schema-locations=classpath*:/graphql-client/**/*.graphqls

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

grpc.client.subdel.address=static://localhost:9090
grpc.client.subdel.negotiation-type=plaintext
grpc.client.analytics-service.address=static://localhost:9091
grpc.client.analytics-service.negotiation-type=plaintext

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

management.metrics.export.prometheus.enabled=true
